name = "mailrelay"
main = "src/index.ts"
compatibility_date = "2024-10-31"

# Environment variables (secrets should be set via `wrangler secret put`)
# PERSONAL_EMAIL - set via wrangler secret
# WORK_EMAIL - set via wrangler secret
# PINCODE - set via wrangler secret
# FROM_EMAIL - set via wrangler secret
# FROM_NAME - set via wrangler secret
